###
GET http://localhost:3000/api/
###
PUT http://localhost:3000/api/create
###
GET http://localhost:3000/api/nested-create?hello=world
Content-Type: application/json

{
  "key": "world"
}
###
GET http://localhost:3000/api/class?foo=bar